# Site settings
author:
title:
email:
description:
keywords:
baseurl:
url:

# Info
skills:

# Social media
social:
  - title:
    url:
  - title:
    url:
  - title:
    url:


permalink:

# Webmaster settings
google_verify:
bing_verify:

# Copyright
credits:

# Build settings
markdown: kramdown
permalink: pretty

# Exclude the following from Jekyll processing when building _site
exclude: [ Gemfile, Gemfile.lock, yarn.lock, node_modules, package.json ]