# Site settings
author: Thomas Harmon
title: Project Pluto
email: harmonbiz808@gmail.com
description: Combing duality with reality to find the holy trinity.
keywords: Hype, clothes, designer, supreme, gucci, louis vutton, balenciaga, off white, resell, limited, custom, boutique, private, collection, consignment, premium, luxury, 
baseurl: 
url:

# Info
skills:

# Social media
social:
  - title: Facebook
    url:
  - title: Instagram
    url:
  - title: Snapchat
    url:


permalink:

# Webmaster settings
google_verify:
bing_verify:

# Copyright
credits:

# Build settings
markdown: kramdown
permalink: pretty

# Exclude the following from Jekyll processing when building _site
exclude: [ Gemfile, Gemfile.lock, yarn.lock, node_modules, package.json ]